-- Таблица отзывов для публичной формы сайта.
-- Выполняйте только если таблица comments ещё не создана.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 60),
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 2 and 600),
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Public can read comments" on public.comments;
create policy "Public can read comments"
  on public.comments for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can add comments" on public.comments;
create policy "Public can add comments"
  on public.comments for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public cannot update comments" on public.comments;
create policy "Public cannot update comments"
  on public.comments for update
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "Public cannot delete comments" on public.comments;
create policy "Public cannot delete comments"
  on public.comments for delete
  to anon, authenticated
  using (false);
